# Generated by Django 4.2.23 on 2025-09-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="owner",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
