# Generated by Django 4.2.23 on 2025-09-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_card_owner"),
    ]

    operations = [
        migrations.RemoveField(model_name="card", name="owner",),
    ]
