# Generated by Django 4.2.23 on 2025-09-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_card_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="phone",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
