# Generated by Django 4.2.23 on 2025-09-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_card_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card", name="title", field=models.CharField(max_length=200),
        ),
    ]
