# Generated by Django 4.2.23 on 2025-09-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_card_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("age", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
