# Generated by Django 4.2.23 on 2025-11-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
        ),
    ]
