# Generated by Django 4.2.23 on 2025-11-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.department",
            ),
        ),
    ]
